name: Our Workflow
on: push
permissions:
  id-token: write
  pages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
      - uses: actions/cache@v4
        with:
          path: .stack-work
          key: ${{ runner.os }}-${{ hashFiles(site.hs) }}
      - run: |
          stack build
          stack exec myblog build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
      - uses: actions/deploy-pages@v4
