name: Our Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.stack 
          key: ${{ runner.os }}-${{ hashFiles('**/stack.yaml.lock')
      - run: |
          stack build
          stack exec myblog clean
          stack exec myblog build
      - uses: actions/deploy-pages@v4
