name: Our Workflow
on: push
permissions:
  id-token: write
  pages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          stack --stack-yaml stack.yaml build
          stack exec myblog build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
      - uses: actions/deploy-pages@v4
